### ISSUE TITLE
网络请求异常

### ISSUE THREAD

**Issue by fuhaichao122** [chenliang2016/CLReactAntDesign#1]
您好，首先谢谢您的开源。我跑项目了，但是登陆的时候报错，进不去，由于不太懂，想请教一下。麻烦给看看，谢谢了。
POST http://localhost:9000/api/auth/login 500 (Internal Server Error)
index.js:6279 Uncaught (in promise) Error: Objects are not valid as a React child (found: Error: 网络请求异常). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons.
    at invariant (index.js:6279)
    at traverseAllChildrenImpl (index.js:58236)
    at traverseAllChildren (index.js:58264)
    at Object.instantiateChildren (index.js:102552)
    at ReactDOMComponent._reconcilerInstantiateChildren (index.js:107293)
    at ReactDOMComponent.mountChildren (index.js:107332)
    at ReactDOMComponent._createInitialChildren (index.js:104388)
    at ReactDOMComponent.mountComponent (index.js:104207)
    at Object.mountComponent (index.js:15156)
    at ReactDOMComponent.mountChildren (index.js:107344)
    at ReactDOMComponent._createInitialChildren (index.js:104388)
    at ReactDOMComponent.mountComponent (index.js:104207)
    at Object.mountComponent (index.js:15156)
    at ReactDOMComponent.mountChildren (index.js:107344)
    at ReactDOMComponent._createInitialChildren (index.js:104388)
    at ReactDOMComponent.mountComponent (index.js:104207)

**Comment by fuhaichao122** [comment]
npm中这样报错

Listening on port 9000. Open up http://localhost:9000/ in your browser.
webpack built 56f4b279b9181d9edfdd in 14095ms
Error: connect ECONNREFUSED 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)


app started in 8080

  Error: connect ECONNREFUSED 127.0.0.1:3306
      at Object.exports._errnoException (util.js:1024:11)
      at exports._exceptionWithHostPort (util.js:1047:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)

**Comment by chenliang2016** [comment]
@fuhaichao122 ,我这个有个后台程序，server文件夹下面是一些接口，并且我是用的mysql数据库，请问你本地是否安装了mysql数据库，并且把我的数据库脚本运行进去。然后检查下，server是否正常运行。然后启动前端的页面。

**Comment by fuhaichao122** [comment]
@chenliang2016 ,原来是这样啊，我本地没有安装mysql，我对后台不太懂。那我要想正常跑起来，是不是先安装mysql，然后再按您文档说的后台那里操作。就可以呢？还是有其他的办法呢？

**Comment by chenliang2016** [comment]
是的，后台服务是用koa2写的。是一些模块管理这些。可以先了解下，后台的一些东西。按照我的步骤把后台跑起来再看看。
